version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  dev:
    build:
      context: .
      target: builder
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    profiles:
      - dev 